CREATE TABLE student (name TEXT, grade REAL, piazza INTEGER);
INSERT INTO student VALUES ('James', 4.0, 1);
INSERT INTO student VALUES ('Yaxin', 4.0, 2);
INSERT INTO student VALUES ('Li', 3.2, 2);
SELECT * FROM student ORDER BY piazza, grade;
CREATE TABLE student2 (name TEXT, grade REAL, piazza INTEGER);
INSERT INTO student2 VALUES ('James', 3.5, 1);
INSERT INTO student2 VALUES ('Yaxin', 2.0, 2);
INSERT INTO student2 VALUES ('Li', 2.3, 2);
SELECT * FROM student2 ORDER BY piazza, grade;