1: BEGIN TRANSACTION;
1: COMMIT TRANSACTION;
1: BEGIN DEFERRED TRANSACTION;
1: COMMIT TRANSACTION;
1: BEGIN IMMEDIATE TRANSACTION;
1: COMMIT TRANSACTION;
1: BEGIN EXCLUSIVE TRANSACTION;
1: COMMIT TRANSACTION;
